# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site favicons & manifest icons
# 9. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- alembic-jekyll-theme.gemspec
- .jekyll-cache

# 2. Installed Gems
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji

remote_theme: daviddarnes/alembic

# 3. Gem settings
paginate: 2 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
twitter:
  username:  # jekyll-seo-tag > Owners twitter username
author:
  name             : "Adam Gajtkowki"
  avatar           : "/images/profile.jpeg" # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio              : "Data Science Portfolio"
  location         : "Financial Times"
  email            : "adam.gajtkowski@icloud.com"
  links:
    - label: "Email"
      icon: "adam.gajtkowski@icloud.com"
      # url: mailto:adam.gajtkowski@icloud.com
    - label: "Website"
      icon: "fas fa-fw fa-link"
      # url: "https://your-website.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      # url: "https://twitter.com/"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      # url: "https://facebook.com/"
    - label: "GitHub"
      icon: "adam9601"
      # url: "https://github.com/adam9601"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      # url: "https://instagram.com/"  

social: # jekyll-seo-tag > social overrides
  name: Jiamu Jiang # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://www.linkedin.com/in/jiamu-j-6b107516a/
    - https://github.com/jiajia-404/
# markdown: CommonMark # Markdown parse settings, CommonMark performs slightly better an others in build time
# commonmark:
  # options: ["SMART", "FOOTNOTES"]
  # extensions: ["strikethrough", "autolink", "table"]

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Europe/London # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    title: Posts # Needed for Siteleaf
    output: true
    description: "" # The post list page content
    #feature_text: |
     # Welcome to the blog
    #feature_image: "https://picsum.photos/2560/600?image=866"

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
    values:
      image: "/assets/default-social-image.png" # Default image for sharing


# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: en-GB # Set the site language
title: "Jiamu Jiang" # Site name or title, also used in jekyll-seo-tag
logo:  # Site logo, also used in jekyll-seo-tag
description: "Computational Neuroscience" # Site description and default description, also used in jekyll-seo-tag
url: "https://github.com/jiajia-404" # Site url, also used in jekyll-seo-tag
baseurl: ""
repo: "https://github.com/jiajia-404"
email: "jiamu.jiang@nottingham.ac.uk"
# disqus: "alembic-1" # Blog post comments, uncomment the option and set the site ID from your Disqus account
# google_analytics: ''
# google_analytics_anonymize_ip: ''
# service_worker: false # Will turn off the service worker if set to false
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

# 8. Site favicons & manifest icons
favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  #16: '/assets/logos/logo@16px.png'
 # 32: '/assets/logos/logo@32px.png'
  #96: '/assets/logos/logo@96px.png'
  #120: '/assets/logos/logo@120px.png'
  #144: '/assets/logos/logo@144px.png'
  #180: '/assets/logos/logo@180px.png'
  #512: '/assets/logos/logo@512px.png'
  #1024: '/assets/logos/logo@1024px.png'

# 9. Site navigation
navigation_header:
- title: Home
  url: /
- title: CV
  url: /CV/
- title: Projects
  url: /Projects/
- title: Publications
  url: /Publications/
- 

navigation_footer:
- title: 
  url: 


social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  LinkedIn: https://www.linkedin.com/in/jiamu-j-6b107516a/
  GitHub: https://github.com/jiajia-404/
  link: https://jiajia-404.github.io/
  RSS: /feed.xml
